/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        boolean prime = n > 1;
        for(int i = 2; i<= Math.sqrt(n); i++) if(n%i==0) prime = false;
        return prime;
    }
    public long firstPrimeNumberIn(String n) {
        for(int i = 0; i<n.length(); i++)
        {
            boolean prime = isPrime(Long.parseLong(n.substring(i,i+10)));
            if(prime)
            {
                return Long.parseLong(n.substring(i,i+10));
            }   
        }
        return -1;
    }
}
